#!/usr/bin/env python3
"""codegen — a code that codes.

A zero-dependency code generator. Point it at what you want and it prints
ready-to-run Python source to stdout (or a file with -o).

Examples:
    python codegen.py class Point --fields x:float y:float
    python codegen.py cli greet --args name --flags loud
    python codegen.py api todo --routes list get create
    python codegen.py quine
"""

from __future__ import annotations

import argparse
import keyword
import sys
import textwrap


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def _check_ident(name: str) -> str:
    if not name.isidentifier() or keyword.iskeyword(name):
        raise SystemExit(f"codegen: {name!r} is not a valid Python identifier")
    return name


def _parse_field(spec: str) -> tuple[str, str]:
    """'x:float' -> ('x', 'float'); bare 'x' defaults to str."""
    name, _, typ = spec.partition(":")
    return _check_ident(name), (typ or "str")


# --------------------------------------------------------------------------
# generators
# --------------------------------------------------------------------------

def gen_class(name: str, fields: list[str]) -> str:
    cls = _check_ident(name)
    parsed = [_parse_field(f) for f in fields] or [("value", "str")]
    field_lines = "\n".join(f"    {n}: {t}" for n, t in parsed)
    demo_args = ", ".join(f"{n}={t}()" for n, t in parsed)
    return textwrap.dedent(f'''\
        from dataclasses import dataclass, asdict


        @dataclass
        class {cls}:
        {{fields}}

            def to_dict(self) -> dict:
                return asdict(self)


        if __name__ == "__main__":
            print({cls}({demo_args}))
        ''').replace("{fields}", field_lines)


def gen_cli(name: str, args: list[str], flags: list[str]) -> str:
    prog = _check_ident(name)
    lines = [f'    parser = argparse.ArgumentParser(prog="{prog}")']
    for a in args:
        lines.append(f'    parser.add_argument("{_check_ident(a)}")')
    for f in flags:
        lines.append(f'    parser.add_argument("--{_check_ident(f)}", action="store_true")')
    body = "\n".join(lines)
    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """{prog} — generated by codegen."""

        import argparse


        def main() -> None:
        {{body}}
            opts = parser.parse_args()
            print(vars(opts))


        if __name__ == "__main__":
            main()
        ''').replace("{body}", body)


def gen_api(name: str, routes: list[str]) -> str:
    resource = _check_ident(name)
    handlers = "\n".join(
        textwrap.indent(textwrap.dedent(f'''\
            if path == "/{resource}/{_check_ident(r)}":
                return {{"route": "{r}", "resource": "{resource}"}}
            '''), "    ")
        for r in (routes or ["index"])
    )
    return textwrap.dedent(f'''\
        #!/usr/bin/env python3
        """Tiny stdlib HTTP API for '{resource}' — generated by codegen."""

        import json
        from http.server import BaseHTTPRequestHandler, HTTPServer


        def dispatch(path: str):
        {{handlers}}
            return None


        class Handler(BaseHTTPRequestHandler):
            def do_GET(self):
                result = dispatch(self.path)
                self.send_response(200 if result else 404)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                payload = result if result else {{"error": "not found"}}
                self.wfile.write(json.dumps(payload).encode())


        if __name__ == "__main__":
            print("serving on http://127.0.0.1:8000")
            HTTPServer(("127.0.0.1", 8000), Handler).serve_forever()
        ''').replace("{handlers}", handlers.rstrip())


def gen_quine() -> str:
    # A program whose output is its own source: code that codes itself.
    quine = 's = %r\nprint(s %% s, end="")\n'
    return quine % quine


# --------------------------------------------------------------------------
# entry point
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    # SUPPRESS keeps a subparser's unset -o from clobbering one given
    # before the subcommand (argparse parents + subparsers gotcha).
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("-o", "--output", default=argparse.SUPPRESS,
                        help="write to file instead of stdout")

    parser = argparse.ArgumentParser(
        prog="codegen",
        description="A code that codes: generates runnable Python source.",
        parents=[common],
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_class = sub.add_parser("class", help="generate a dataclass", parents=[common])
    p_class.add_argument("name")
    p_class.add_argument("--fields", nargs="*", default=[], metavar="name:type")

    p_cli = sub.add_parser("cli", help="generate an argparse CLI", parents=[common])
    p_cli.add_argument("name")
    p_cli.add_argument("--args", nargs="*", default=[])
    p_cli.add_argument("--flags", nargs="*", default=[])

    p_api = sub.add_parser("api", help="generate a stdlib HTTP API", parents=[common])
    p_api.add_argument("name")
    p_api.add_argument("--routes", nargs="*", default=[])

    sub.add_parser("quine", help="generate a program that prints itself",
                   parents=[common])

    opts = parser.parse_args(argv)

    if opts.command == "class":
        source = gen_class(opts.name, opts.fields)
    elif opts.command == "cli":
        source = gen_cli(opts.name, opts.args, opts.flags)
    elif opts.command == "api":
        source = gen_api(opts.name, opts.routes)
    else:
        source = gen_quine()

    compile(source, "<generated>", "exec")  # refuse to emit broken code

    output = getattr(opts, "output", None)
    if output:
        with open(output, "w") as fh:
            fh.write(source)
        print(f"wrote {output}", file=sys.stderr)
    else:
        sys.stdout.write(source)


if __name__ == "__main__":
    main()
